[package]
name = "my-package"
version = "1.0.0"
authors = []
edition = "2018"

[dependencies]
dependency-a = "0.0.0"
dependency-b = "0.0.0"

[dev-dependencies]
dependency-c = "0.0.0"
dependency-d = "0.0.0"
